### ISSUE TITLE
Add package doc comment to make gocarina searchable at GoDoc.org

### ISSUE THREAD

**Issue by mewmew** [armhold/gocarina#1]
It should be possible to locate the gocarina package by performing a search for [OCR on GoDoc.org](https://godoc.org/?q=OCR). Include a package doc comment to make is searchable.

**Comment by armhold** [comment]
Thanks, fixed in 8699977b33f3b2106d6aca17c8bb2427e31aa818.

**Comment by mewmew** [comment]
Lovely. Now it turns up on GoDoc.org when searching for OCR. Thanks!
